[package]
name = "binary"
version = "0.1.0"
edition = "2021"

[dependencies]
library = { path = "../library" }
tokio = { version = "1", features = ["full"] }
structopt = "*"  # will be resolved to same version as lib due to shared lockfile
